# Generated by Django 5.2.7 on 2025-10-18 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('opportunity_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('agency_code', models.CharField(blank=True, max_length=20, null=True)),
                ('agency_name', models.CharField(blank=True, max_length=200, null=True)),
                ('award_floor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('award_ceiling', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('close_date', models.DateField(blank=True, null=True)),
                ('category_of_funding_activity', models.CharField(blank=True, max_length=200, null=True)),
                ('eligible_applicants', models.TextField(blank=True, null=True)),
                ('cost_sharing_or_matching_requirement', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-close_date', 'title'],
                'indexes': [models.Index(fields=['agency_code'], name='api_grant_agency__3a0124_idx'), models.Index(fields=['close_date'], name='api_grant_close_d_a45436_idx'), models.Index(fields=['title'], name='api_grant_title_247d56_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResearcherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('school', models.CharField(blank=True, max_length=200, null=True)),
                ('expertise', models.JSONField(blank=True, default=list)),
                ('education', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('contact', models.JSONField(blank=True, default=dict)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['department'], name='api_researc_departm_90f4b5_idx'), models.Index(fields=['school'], name='api_researc_school_6abc4f_idx'), models.Index(fields=['name'], name='api_researc_name_618c92_idx')],
            },
        ),
    ]
