# Generated by Django 5.2.7 on 2025-10-18 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='additional_information_on_eligibility',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='additional_information_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='additional_information_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='archive_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='category_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='cfda_numbers',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='close_date_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='estimated_total_program_funding',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='grant',
            name='expected_number_of_awards',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='funding_instrument_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='grantor_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='grantor_contact_email_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='grantor_contact_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='grantor_contact_phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='grantor_contact_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='last_updated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='opportunity_category',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='opportunity_category_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='opportunity_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='post_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='researcherprofile',
            name='publications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='researcherprofile',
            name='education',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
