# Generated by Django 5.2.7 on 2025-10-18 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_grant_additional_information_on_eligibility_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('school', models.CharField(blank=True, max_length=200, null=True)),
                ('university', models.CharField(blank=True, max_length=200, null=True)),
                ('research_areas', models.JSONField(blank=True, default=list)),
                ('expertise_keywords', models.JSONField(blank=True, default=list)),
                ('research_interests', models.TextField(blank=True, null=True)),
                ('current_projects', models.TextField(blank=True, null=True)),
                ('education', models.JSONField(blank=True, default=list)),
                ('publications', models.JSONField(blank=True, default=list)),
                ('awards', models.JSONField(blank=True, default=list)),
                ('grants_received', models.JSONField(blank=True, default=list)),
                ('preferred_agencies', models.JSONField(blank=True, default=list)),
                ('preferred_funding_types', models.JSONField(blank=True, default=list)),
                ('preferred_award_ranges', models.JSONField(blank=True, default=dict)),
                ('preferred_duration', models.JSONField(blank=True, default=dict)),
                ('preferred_locations', models.JSONField(blank=True, default=list)),
                ('travel_willingness', models.CharField(choices=[('none', 'No travel required'), ('minimal', 'Minimal travel'), ('moderate', 'Moderate travel'), ('extensive', 'Extensive travel')], default='moderate', max_length=20)),
                ('collaboration_style', models.CharField(choices=[('solo', 'Solo research'), ('small_team', 'Small team (2-5 people)'), ('large_team', 'Large team (5+ people)'), ('any', 'Any team size')], default='any', max_length=20)),
                ('max_applications_per_year', models.IntegerField(default=10)),
                ('preferred_application_deadline_lead_time', models.IntegerField(default=30)),
                ('contact_info', models.JSONField(blank=True, default=dict)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['department'], name='api_profess_departm_36470b_idx'), models.Index(fields=['school'], name='api_profess_school_6ab695_idx'), models.Index(fields=['university'], name='api_profess_univers_8bfbec_idx'), models.Index(fields=['is_active'], name='api_profess_is_acti_2130c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='GrantRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_score', models.FloatField(default=0.0)),
                ('content_similarity_score', models.FloatField(default=0.0)),
                ('llm_relevance_score', models.FloatField(default=1.0)),
                ('is_viewed', models.BooleanField(default=False)),
                ('is_saved', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('is_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('saved_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_recommendations', to='api.grant')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_recommendations', to='api.professor')),
            ],
            options={
                'ordering': ['-recommendation_score', '-created_at'],
                'indexes': [models.Index(fields=['professor', 'recommendation_score'], name='api_grantre_profess_b3394f_idx'), models.Index(fields=['professor', 'is_dismissed'], name='api_grantre_profess_30ec31_idx'), models.Index(fields=['professor', 'is_saved'], name='api_grantre_profess_d0cada_idx')],
                'unique_together': {('professor', 'grant')},
            },
        ),
    ]
