# Generated by Django 5.2.7 on 2025-10-18 14:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_professor_grantrecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('session_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('professor_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='api.professor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='api_profess_email_150472_idx'), models.Index(fields=['session_token'], name='api_profess_session_465d53_idx')],
            },
        ),
    ]
