# Generated by Django 5.2.7 on 2025-10-18 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_professoruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('collaborator', 'Collaborator'), ('co_pi', 'Co-Principal Investigator'), ('advisor', 'Advisor'), ('consultant', 'Consultant')], max_length=20)),
                ('contribution_notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='CollaborationInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_email', models.EmailField(max_length=254)),
                ('invitee_name', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('role', models.CharField(choices=[('collaborator', 'Collaborator'), ('co_pi', 'Co-Principal Investigator'), ('advisor', 'Advisor'), ('consultant', 'Consultant')], default='collaborator', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('allow_anonymous', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('edit_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('helpful', 'Helpful'), ('insightful', 'Insightful')], default='like', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('applying', 'Applying'), ('submitted', 'Submitted'), ('awarded', 'Awarded'), ('rejected', 'Rejected')], default='saved', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('allow_collaboration', models.BooleanField(default=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('reply_count', models.PositiveIntegerField(default=0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_pinned', '-last_activity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_on_reply', models.BooleanField(default=True)),
                ('notify_on_like', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='grant',
            name='catholic_social_teaching_compliance',
            field=models.CharField(choices=[('compliant', 'Compliant'), ('flagged', 'Flagged for Review'), ('non_compliant', 'Non-Compliant'), ('not_reviewed', 'Not Reviewed')], default='not_reviewed', help_text='Flag indicating alignment with Catholic social teaching principles', max_length=20),
        ),
        migrations.AddField(
            model_name='grant',
            name='catholic_social_teaching_notes',
            field=models.TextField(blank=True, help_text='Notes about Catholic social teaching compliance review', null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='catholic_social_teaching_reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When this grant was last reviewed for Catholic social teaching compliance', null=True),
        ),
        migrations.AddIndex(
            model_name='grant',
            index=models.Index(fields=['catholic_social_teaching_compliance'], name='api_grant_catholi_5eb75d_idx'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='api.professoruser'),
        ),
        migrations.AddField(
            model_name='collaborationinvite',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to='api.professoruser'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='invite',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration', to='api.collaborationinvite'),
        ),
        migrations.AddIndex(
            model_name='forum',
            index=models.Index(fields=['is_active', 'order'], name='api_forum_is_acti_46fc5f_idx'),
        ),
        migrations.AddIndex(
            model_name='forum',
            index=models.Index(fields=['slug'], name='api_forum_slug_3ad82f_idx'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_posts', to='api.professoruser'),
        ),
        migrations.AddField(
            model_name='post',
            name='parent_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.post'),
        ),
        migrations.AddField(
            model_name='postlike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.post'),
        ),
        migrations.AddField(
            model_name='postlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='api.professoruser'),
        ),
        migrations.AddField(
            model_name='savedgrant',
            name='grant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='api.grant'),
        ),
        migrations.AddField(
            model_name='savedgrant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_grants', to='api.professoruser'),
        ),
        migrations.AddField(
            model_name='collaborationinvite',
            name='grant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_invites', to='api.savedgrant'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='grant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='api.savedgrant'),
        ),
        migrations.AddField(
            model_name='topic',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_topics', to='api.professoruser'),
        ),
        migrations.AddField(
            model_name='topic',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='api.forum'),
        ),
        migrations.AddField(
            model_name='topic',
            name='last_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_post_in_topic', to='api.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='api.topic'),
        ),
        migrations.AddField(
            model_name='topicsubscription',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='api.topic'),
        ),
        migrations.AddField(
            model_name='topicsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_subscriptions', to='api.professoruser'),
        ),
        migrations.AddIndex(
            model_name='postlike',
            index=models.Index(fields=['post', 'like_type'], name='api_postlik_post_id_d22d7d_idx'),
        ),
        migrations.AddIndex(
            model_name='postlike',
            index=models.Index(fields=['user', '-created_at'], name='api_postlik_user_id_d25513_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('post', 'user')},
        ),
        migrations.AddIndex(
            model_name='savedgrant',
            index=models.Index(fields=['user', 'status'], name='api_savedgr_user_id_9d800a_idx'),
        ),
        migrations.AddIndex(
            model_name='savedgrant',
            index=models.Index(fields=['user', 'saved_at'], name='api_savedgr_user_id_446067_idx'),
        ),
        migrations.AddIndex(
            model_name='savedgrant',
            index=models.Index(fields=['is_public'], name='api_savedgr_is_publ_1881a0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedgrant',
            unique_together={('user', 'grant')},
        ),
        migrations.AddIndex(
            model_name='collaborationinvite',
            index=models.Index(fields=['invitee_email', 'status'], name='api_collabo_invitee_bc170a_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborationinvite',
            index=models.Index(fields=['inviter', 'status'], name='api_collabo_inviter_650203_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborationinvite',
            index=models.Index(fields=['grant', 'status'], name='api_collabo_grant_i_8a7aa0_idx'),
        ),
        migrations.AddIndex(
            model_name='collaboration',
            index=models.Index(fields=['grant', 'is_active'], name='api_collabo_grant_i_9b0653_idx'),
        ),
        migrations.AddIndex(
            model_name='collaboration',
            index=models.Index(fields=['collaborator', 'is_active'], name='api_collabo_collabo_6bf6ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collaboration',
            unique_together={('grant', 'collaborator')},
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['forum', '-last_activity'], name='api_topic_forum_i_a25058_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['author', '-created_at'], name='api_topic_author__c6dac8_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['-created_at'], name='api_topic_created_14e68a_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['topic', 'created_at'], name='api_post_topic_i_3e669c_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-created_at'], name='api_post_author__387d67_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['parent_post'], name='api_post_parent__a0164b_idx'),
        ),
        migrations.AddIndex(
            model_name='topicsubscription',
            index=models.Index(fields=['user', '-created_at'], name='api_topicsu_user_id_9e2a61_idx'),
        ),
        migrations.AddIndex(
            model_name='topicsubscription',
            index=models.Index(fields=['topic'], name='api_topicsu_topic_i_d4e98f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='topicsubscription',
            unique_together={('topic', 'user')},
        ),
    ]
