# Generated by Django 5.2.7 on 2025-10-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_catholic_social_teaching_compliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='capability_and_strategy',
            field=models.TextField(blank=True, help_text='Description of research capabilities, expertise, and strategy for using the grant matching platform', null=True),
        ),
    ]
