# Generated by Django 5.2.7 on 2025-10-18 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_professor_capability_and_strategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantPipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('color', models.CharField(default='#16B1FF', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grants', models.ManyToManyField(blank=True, related_name='pipeline_stages', to='api.grant')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_stages', to='api.professor')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('professor', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GrantPipelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('application_submitted_date', models.DateField(blank=True, null=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('decision_status', models.CharField(choices=[('pending', 'Pending'), ('awarded', 'Awarded'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moved_to_stage_at', models.DateTimeField(auto_now_add=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_entries', to='api.grant')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_entries', to='api.professor')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api.grantpipelinestage')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['professor', 'stage'], name='api_grantpi_profess_a64422_idx'), models.Index(fields=['professor', 'priority'], name='api_grantpi_profess_30a16e_idx'), models.Index(fields=['application_deadline'], name='api_grantpi_applica_b622e3_idx')],
                'unique_together': {('professor', 'grant')},
            },
        ),
    ]
