# Generated by Django 5.2.7 on 2025-10-18 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0004_professoruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('review', 'Under Review'), ('submitted', 'Submitted'), ('rejected', 'Rejected'), ('awarded', 'Awarded')], default='draft', max_length=20)),
                ('project_summary', models.TextField(blank=True, null=True)),
                ('research_objectives', models.TextField(blank=True, null=True)),
                ('methodology', models.TextField(blank=True, null=True)),
                ('expected_outcomes', models.TextField(blank=True, null=True)),
                ('budget_justification', models.TextField(blank=True, null=True)),
                ('timeline', models.TextField(blank=True, null=True)),
                ('team_description', models.TextField(blank=True, null=True)),
                ('institutional_support', models.TextField(blank=True, null=True)),
                ('broader_impacts', models.TextField(blank=True, null=True)),
                ('ai_generated', models.BooleanField(default=True)),
                ('generation_prompt', models.TextField(blank=True, null=True)),
                ('generation_model', models.CharField(blank=True, max_length=100, null=True)),
                ('generation_confidence', models.FloatField(default=0.0)),
                ('user_notes', models.TextField(blank=True, null=True)),
                ('custom_sections', models.JSONField(blank=True, default=dict)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_edited_by', models.CharField(blank=True, max_length=200, null=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='api.grant')),
                ('parent_draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_drafts', to='proposals.grantdraft')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_drafts', to='api.professor')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['professor', 'status'], name='proposals_g_profess_1aae81_idx'), models.Index(fields=['professor', 'grant'], name='proposals_g_profess_06af77_idx'), models.Index(fields=['status'], name='proposals_g_status_da7b8a_idx'), models.Index(fields=['created_at'], name='proposals_g_created_f1d76a_idx')],
            },
        ),
    ]
